### ISSUE TITLE
Changes to Node.js `exports` specification

### ISSUE THREAD

**Issue by merceyz** [lukeed/resolve.exports#11]
Node.js has changed their `exports` specification deprecating trailing slash pattern mappings in https://github.com/nodejs/node/pull/40039 and added support for pattern trailers in https://github.com/nodejs/node/pull/39635 so some changes might be required.

**Comment by lukeed** [comment]
This is already supported. The deprecated syntax will continue to be supported because it's still widely used and Node also supports it (and will for a long time as it's part of LTS)
