### ISSUE TITLE
Throw on invalid package target

### ISSUE THREAD

**Issue by paul-soporan** [lukeed/resolve.exports#5]
Node throws `ERR_INVALID_PACKAGE_TARGET` when a package target doesn't start with `./`.

`resolve.exports` doesn't throw anything.

```ts
const pkgJson = {
  exports: {
    './a': '../b',
    './c': 'd',
  }
};

resolve(pkgJson, './a'); // passes but not allowed by node
resolve(pkgJson, './c'); // passes but not allowed by node
```

Ref:
- https://nodejs.org/api/esm.html#esm_resolver_algorithm
- https://github.com/nodejs/node/blob/2af43f65055de2817eb7907d3a3d3b3a3de127f5/lib/internal/modules/esm/resolve.js#L368

**Comment by lukeed** [comment]
This module is not a validator –  _only_ resolves existing `exports` mappings & returns what's defined.

Because the value is returned as defined (except subpatterns, which are evaluated), this is trivial to apply on the returned output string.

**Comment by paul-soporan** [comment]
Thanks for the explanation! Perhaps you could put a non-goals section inside the README so that people know exactly which parts of the Node exports resolution ("resolution" might not be the best word as sometimes resolvers include validation and sometimes they don't) they have to implement themselves.
