### ISSUE TITLE
Order of paths in exports object shouldn't matter

### ISSUE THREAD

**Issue by bgotink** [lukeed/resolve.exports#7]
The following two exports objects are equivalent for Node, but `resolve.exports` only works correctly for the first. This can be verified by swapping lines 401 and 402 in `test/resolve.js`

```json
{
  "./data/*": "./data/*.json",
  "./": "./"
}

{
  "./": "./",
  "./data/*": "./data/*.json"
}
```

Looking at the ESM resolution algorithm in node's documentation (`PACKAGE_IMPORTS_EXPORTS_RESOLVE` [here](https://nodejs.org/api/esm.html#esm_resolver_algorithm_specification)), node sorts the keys by key length before looking for a match.

**Comment by lukeed** [comment]
Thanks, missed that. Can't quite get to this right now, but should be very easy to implement.

**Comment by bgotink** [comment]
I hope you don't mind I gave it a go.

Rather than actually sorting as mentioned in the node docs I've chosen to loop through the entire object, as sorting would get slower for larger export objects.

**Comment by unional** [comment]
btw I have released [pattern-key-compare](https://github.com/cyberuni/resolve.imports/blob/main/packages/pattern-key-compare/README.md) for [resolve.imports](https://github.com/cyberuni/resolve.imports/blob/main/packages/resolve.imports/README.md), in case you want to use it.
