### ISSUE TITLE
Incorrect substitution with multiple * wildcards

### ISSUE THREAD

**Issue by evanw** [lukeed/resolve.exports#9]
I looked at this library briefly when I implemented this feature for esbuild and discovered some bugs. One of them is that it looks like this library doesn't handle `*` wildcards correctly when there are multiple wildcards:

```js
const re = require('resolve.exports')
const pkg = {
  exports: {
    "./dir*": "./*sub/dir*/file.js"
  }
}
console.log(re.resolve(pkg, 'dirtest'))
```

Expected output:

```js
./testsub/dirtest/file.js
```

Observed output:

```js
./testsub/dir*/file.js
```

The relevant part from [the spec](https://nodejs.org/api/esm.html#esm_resolver_algorithm_specification) is this one:

>    7. If _pattern_ is **true**, then
>       1. Return the URL resolution of _resolvedTarget_ with every instance of _"*"_ replaced with _subpath_.

Other bugs I found included #7 and missing validation checks. I wasn't sure whether to also file a bug about the missing validation checks since you could argue that it's potentially not a concern of this library, although if many tools are adopting this package then it would probably make sense to put the validation checks in one place instead of replicating them in the various projects.

**Comment by lukeed** [comment]
Oh right, missed this. Thank you!

Validation checks of the target path(s) are implemented as part of #6 – I'm still waiting on general consensus as to whether or not others feel _this_ library should be responsible for them.

**Comment by ljharb** [comment]
Are you sure node itself supports multiple wildcards?

**Comment by huntie** [comment]
Hmm, I'm not sure this is the intended resolution behaviour in the spec.

Here you've quoted a step from the `PACKAGE_TARGET_RESOLVE` function in the [resolution algorithm](https://nodejs.org/api/esm.html#esm_resolver_algorithm_specification).

> i. Return the URL resolution of resolvedTarget with every instance of "*" replaced with subpath.

However, this is incongruent with:

1. The definition of `PACKAGE_IMPORTS_EXPORTS_RESOLVE` (relevant to the package.json exports field) which explicitly notes the single wildcard handling (pattern trailer).

    ![image](https://user-images.githubusercontent.com/2547783/208733036-dd23d738-1486-46e8-ba3c-3b888a0a2ed3.png)

    This does depend on `PACKAGE_TARGET_RESOLVE` but again explicitly passes `null` to the `patterns` argument (meaning substitution wouldn't be implemented at that level).

    ![image](https://user-images.githubusercontent.com/2547783/208733050-dd51f36b-8d05-49f0-b7f9-e9ad298032e0.png)

2. The examples in the [Subpath patterns](https://nodejs.org/docs/latest-v18.x/api/packages.html#subpath-patterns) section of the Packages spec, and the note on the implementing PR: https://github.com/nodejs/node/pull/39635.

> 3. Multiple * can't be matched in patterns, so given "exports": { "./*/*.js": "./*.js" } this will no longer match import './*/x.js' and instead throw an unexported error. — https://github.com/nodejs/node/pull/39635#issue-958542966
